name: "Update Angular"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to run the workflow'
        required: true
        default: 'master'
  # schedule:
  #   - cron: '30 5 * * 1,3,5'

jobs:
  ngxUpdate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies
        uses: fast-facts/ng-update@v1
        with:
          base-branch: ${{ github.event.inputs.branch }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
